"""
389. Find the Difference
https://leetcode.com/problems/find-the-difference/description/?envType=problem-list-v2&envId=hash-table&difficulty=EASY
"""

"""
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

It is good that i remembered about XOR, it is possible to make 2 hashmaps and just XOR them

XOR is possible only for sets, not dicts :( But solution still beats 75% cuz of efficient search
But best solution counts sum by making use of ord(str) and difference between lines perfectly 
represents additional letter
"""


class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        s_map = {}
        for letter in s:
            if letter in s_map:
                s_map[letter] += 1
            else:
                s_map[letter] = 1

        t_map = {}
        for letter in t:
            if letter in s_map:
                s_map[letter] -= 1
            else:
                return letter
        for letter in s_map:
            if s_map[letter] != 0:
                return letter

        